### ISSUE TITLE
Add videos?

### ISSUE THREAD

**Issue by rmark66** [StudentShop/Permits-Upgrades#2]
Do we want to have the You Tube channel or video location added to the Readme files? Or maybe add a Readme to each individual permit upgrade file for this purpose?

**Comment by callhands** [comment]
Yes, we definitly need to add context (link to YouTube, description of training process, etc.). The Tormach-Guide README is more or less how all our README documents should look (Although the main description could be improved by including how the guide is used). They are one of my top priorities when I get back. Without a good README the content is much less usefull.
